### PR TITLE
Fix compat with RubyInstaller-2.4 on Windows

### LINKED ISSUE #861: cannot load such file -- mysql2/2.4/mysql2 (LoadError)`
I am new on Ruby on Rails. My Ruby version is ruby2.4.1p111 (2017-03-22 revision 58053) [x64-mingw32].

I have created a new project using rails new sample_cms -d mysql command.

The command rails server is throwing following error.

C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mysql2-0.4.6-x64-mingw32/lib/mysql2/mysql2.rb:2:inrequire': cannot load such file -- mysql2/2.4/mysql2 (LoadError)`
I have installed mysql and mysql Connector C. I have installed the mysql2 gem like that.

gem install mysql2 —platform=ruby — ‘—with-mysql-dir="C:\Program Files\MySQL\MySQL Connector C 6.1"’
I have uninstall and install the mysql2 gem but still facing the issue. Here is the directory which may have issue.

27505154-7b8f3f4e-58b2-11e7-8c8a-66980553443c

Here is the gem file entry for mysql2

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.1.1'
# Use mysql as the database for Active Record
gem 'mysql2', '>= 0.3.18', '< 0.5'
# Use Puma as the app server
gem 'puma', '~> 3.7'
Any Help?

### PR DESCRIPTION
**Pull request by larskanis**
Since RubyInstaller-2.4+ is bundled with MSYS2 and the libmariadbclient can be installed per gemspec library dependency, it is easy to build the mysql2 gem in Windows.

The MSYS2/MINGW dependency feature is documented here: https://github.com/oneclick/rubyinstaller2/wiki/For-gem-developers#msys2-library-dependency

This also adds ruby-2.4 binaries (per rake-compiler-dock-0.6.0), so that the mysql2 is still useabel as a binary gem.

Fixes #861

The change in the spec is required for mariadbclient. It throws an error if no query was executed.

Due to the stdcall convention on i686, the mysql_query() function check fails, so that it is omitted, now.

### CODE REVIEW

File: lib/mysql2.rb [hunk 1]
```diff
@@ -13,16 +13,20 @@
     ENV['RUBY_MYSQL2_LIBMYSQL_DLL']
   elsif File.exist?(File.expand_path('../vendor/libmysql.dll', File.dirname(__FILE__)))
     # Use vendor/libmysql.dll if it exists, convert slashes for Win32 LoadLibrary
-    File.expand_path('../vendor/libmysql.dll', File.dirname(__FILE__)).tr('/', '\\')
+    File.expand_path('../vendor/libmysql.dll', File.dirname(__FILE__))
```
Comment (sodabrew) [inline lib/mysql2.rb]: I remember the backslashes being required, since the LoadLibrary call is native Windows and not Ruby.

File: lib/mysql2.rb [hunk 2]
```diff
@@ -13,16 +13,20 @@
...
+  elsif defined?(RubyInstaller)
```
Comment (sodabrew) [inline lib/mysql2.rb]: What is `RUBY_PLATFORM` when `RubyInstaller` is defined?

File: spec/mysql2/statement_spec.rb [hunk 3]
```diff
@@ -712,7 +712,6 @@ def stmt_count
 
     it 'should return number of rows affected by an insert' do
       stmt = @client.prepare 'INSERT INTO lastIdTest (blah) VALUES (?)'
-      expect(stmt.affected_rows).to eq 0
```
Comment (sodabrew) [inline spec/mysql2/statement_spec.rb]: Why was this removed?

File: tasks/compile.rake [hunk 4]
```diff
@@ -26,6 +26,10 @@ Rake::ExtensionTask.new("mysql2", Mysql2::GEMSPEC) do |ext|
       Rake::Task['lib/mysql2/mysql2.rb'].invoke
       # vendor/libmysql.dll is invoked from extconf.rb
       Rake::Task['vendor/README'].invoke
+
+      # only the source gem has a package dependency - the binary gem ships it's own DLL version
```
Comment (sodabrew) [inline tasks/compile.rake]: nit: `its` for the possessive :)

File: tasks/compile.rake [hunk 5]
```diff
@@ -77,7 +81,7 @@ task :devkit do
 end
 
 if RUBY_PLATFORM =~ /mingw|mswin/
-  Rake::Task['compile'].prerequisites.unshift 'vendor:mysql'
+  Rake::Task['compile'].prerequisites.unshift 'vendor:mysql' unless defined?(RubyInstaller)
```
Comment (sodabrew) [inline tasks/compile.rake]: I'm not following why the unless RubyInstaller case is needed. This file shouldn't execute in the source code case, only when I'm building the binaries at my desktop.

File: lib/mysql2.rb (hunk 1 above)
Comment (larskanis) [inline lib/mysql2.rb]: LoadLibrary accepts both, forward and backward slashes as all filesystem related WINAPI functions do. There's no need to translate path separators. cmd and powershell don't recognize forward slashs, but can handle them as well.

File: lib/mysql2.rb (hunk 2 above)
Comment (larskanis) [inline lib/mysql2.rb]: `x64-mingw32` and `i386-mingw32` - the same as previous RubyInstaller versions.

File: spec/mysql2/statement_spec.rb (hunk 3 above)
Comment (larskanis) [inline spec/mysql2/statement_spec.rb]: As commented: The change in the spec is required for mariadbclient. It throws an error if no query was executed.

File: tasks/compile.rake (hunk 4 above)
Comment (larskanis) [inline tasks/compile.rake]: Sorry, but thanks for the hint!

File: tasks/compile.rake (hunk 5 above)
Comment (larskanis) [inline tasks/compile.rake]: `rake spec` depends on `compile`, which is OK, but it shouldn't depend on the vendored mysql library on RubyInstaller-2.4.

The reason is: the simplest way to build the mysql2 gem is by using the `libmariadbclient` pacman package. It is automatically installed though the `metadata['msys2_mingw_dependencies']` tag when running `gem install mysql2`

On the other hand the vendored library works as well, provided that the `unzip` command is installed. This can be done per `pacman -S unzip`. But I think that this shouldn't the default way on RubyInstaller-2.4.

**Comment by larskanis** [comment]
Is there anything I can do to get this merged and released?
